<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <Title>NuggetLib.Core</Title>
        <Authors>Matvey Beloded</Authors>
        <Copyright>Copyright (c) Matvey Beloded 2026</Copyright>
        <AssemblyVersion>1.0.0</AssemblyVersion>
        <FileVersion>1.0.0</FileVersion>
        <RepositoryUrl>https://github.com/JustChickNugget/NuggetLib</RepositoryUrl>
        <Description>Common classes and functions that are frequently used</Description>
        <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
        <IsPackable>true</IsPackable>
        <PackageReadmeFile>README.md</PackageReadmeFile>
        <PackageLicenseFile>LICENSE</PackageLicenseFile>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Avalonia" Version="11.3.10"/>
    </ItemGroup>

    <ItemGroup>
        <None Include="README.md" Pack="true" PackagePath="/"/>
        <None Include="../LICENSE" Pack="true" PackagePath="/"/>
    </ItemGroup>

</Project>
